Explicit Decline of offers
adobe-apiplatform/mesos-actor pull request #19
Opened 2018-07-06 11:05 UTC by Himavanth

As per the documentation of mesos, if some offers are accepted, the others in the same lot should implicitly get declined.
But this is not happening in all cases and the offers get blocked as "outstanding offers" as seen in the mesos UI.
Expicitly declining them should do no harm afaics

2018-07-17 05:26 UTC, tysonnorris requested changes

2018-07-17 05:26 UTC, tysonnorris commented on src/main/scala/com/adobe/api/platform/runtime/mesos/MesosClient.scala
> +      execInternal(declineCall)
I think this future is not monitored for success?

2018-07-17 05:26 UTC, tysonnorris commented on src/main/scala/com/adobe/api/platform/runtime/mesos/MesosClient.scala
> +      execInternal(declineCall)
Please add a test?

2018-07-17 05:27 UTC, tysonnorris commented
Docs say that "accept" call will implicitly decline unused offer resources - I was under the impression (wrong?) that unaccepted offers will also be implicitly declined during accept processing. Can you verify that offers end up in a bad state in this case?

2018-07-20 18:12 UTC, Himavanth commented
@tysonnorris Yes the docs do say that. In fact i was under the same impression and was puzzled to see outstanding offers in mesos UI while the sampleHAFramework was not getting the offers of unused resources. 
I don't see the outstanding offers anymore if i decline the offers first and then send the accept.

Though this is consistently reproducible with the sampleHAFramework, i am unsure why we would not see this in any of OW deployments.
Do you think there is something else at work here or is it safe to decline first?

![outstanding_offers](https://user-images.githubusercontent.com/3353114/43018106-27aeb2a8-8c76-11e8-8538-611768397e8d.jpeg)
![unused_agents](https://user-images.githubusercontent.com/3353114/43018108-27f406c8-8c76-11e8-86ba-36179461051e.jpeg)

2018-07-20 23:01 UTC, tysonnorris commented
Is this because the sample framework shuts down without a decline? (and in OW maybe it doesn't do that). 
Also, is there any difference in declining after the accept? (if not, let's do that?)
Also, please check that there is handling of all the future completions, this may not be done currently I think @chetanmeh  pointed this out.
Thanks!

2019-02-28 22:49 UTC, tysonnorris commented
included same functionality in #38

2019-02-28 22:49 UTC, closed without merging